Repository johnbillion/extended-cpts, pull requests merged in 2020-07, with the labels that each got.

#126 option to disable block editor
  src/class-extended-cpt-admin.php
Labels: type:enhancement

#131 Fixes dropdown for hierarchical taxonomies
  src/class-extended-taxonomy-admin.php
Labels: type:bug

#111 Fix args merge:
  src/class-extended-cpt.php
  tests/phpunit/Test.php
Labels: awaiting testing
